name: Build and Push Multiple Docker Images

on:
  workflow_dispatch:
    inputs:
      PG_VERSION:
        description: 'PostgreSQL version (13, 14, 15, etc.)'
        required: true
      PG_PLATFORM:
        description: 'PostgreSQL platform (amd64 or arm64)'
        required: true

env:
  PG_IMAGE: postgres-debugger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
        version: [13, 14, 15, 16]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Go to Dockerfile directory
      run: cd docker

    - name: Build Docker image
      run: docker build --platform "linux/${{ matrix.platform }}" \
        --build-arg "TAG=${{ matrix.version }}" \
        --tag ${{ secrets.DOCKER_USERNAME }}/$PG_IMAGE:${{ matrix.version }}-${{ matrix.platform }} .

    - name: Push Docker image to docker hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/$PG_IMAGE:${{ matrix.version }}-${{ matrix.platform }} 
