name: Build and Push Multiple Docker Images

on:
  workflow_dispatch:

env:
  PG_IMAGE: postgres-debugger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [15]
        platform: 
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: print-vars

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: docker
          platforms: ${{ matrix.platform }}
          build-args: TAG=${{ matrix.version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PG_IMAGE }}:${{ matrix.version }}
